//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emsDALEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class emsDBContext : DbContext
    {
        public emsDBContext()
            : base("name=emsDBContext")
        {
            var _ = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<table_Admin> table_Admin { get; set; }
        public virtual DbSet<table_Bill> table_Bill { get; set; }
        public virtual DbSet<table_Bus> table_Bus { get; set; }
        public virtual DbSet<table_Destination> table_Destination { get; set; }
        public virtual DbSet<table_Event> table_Event { get; set; }
        public virtual DbSet<table_Guard> table_Guard { get; set; }
        public virtual DbSet<table_Manager> table_Manager { get; set; }
        public virtual DbSet<table_Picture> table_Picture { get; set; }
        public virtual DbSet<table_Route> table_Route { get; set; }
        public virtual DbSet<table_User> table_User { get; set; }
    }
}
