//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emsDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_Manager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_Manager()
        {
            this.table_Event = new HashSet<table_Event>();
        }
    
        public int C_Manager_id { get; set; }
        public string manager_name { get; set; }
        public Nullable<long> manager_phone { get; set; }
        public string manager_email { get; set; }
        public string manager_password { get; set; }
        public Nullable<System.DateTime> manager_last_login { get; set; }
        public Nullable<System.DateTime> manager_current_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_Event> table_Event { get; set; }
    }
}
