//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emsDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_Bill
    {
        public int C_Bill_id { get; set; }
        public int f_user_id { get; set; }
        public Nullable<double> bill_paid { get; set; }
        public Nullable<double> bill_return { get; set; }
    
        public virtual table_User table_User { get; set; }
    }
}
