//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emsDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_User()
        {
            this.table_Bill = new HashSet<table_Bill>();
        }
    
        public int C_User_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public long user_phone { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_last_login { get; set; }
        public Nullable<System.DateTime> user_current_login { get; set; }
        public Nullable<int> f_event_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_Bill> table_Bill { get; set; }
        public virtual table_Event table_Event { get; set; }
    }
}
