//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emsDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_Destination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_Destination()
        {
            this.table_Event = new HashSet<table_Event>();
        }
    
        public int C_Destination_id { get; set; }
        public string destination_to { get; set; }
        public string destination_from { get; set; }
        public int f_route_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_Event> table_Event { get; set; }
        public virtual table_Route table_Route { get; set; }
    }
}
