//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emsDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_Admin
    {
        public int C_Admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_password { get; set; }
        public long admin_phone { get; set; }
        public string admin_email { get; set; }
        public Nullable<System.DateTime> admin_last_login { get; set; }
        public Nullable<System.DateTime> admin_current_login { get; set; }
    }
}
